### PR TITLE
Add UCSBOrganization Form, Table Components + Create, Edit, Index Pages

### LINKED ISSUE #19: Form Component for `UCSBOrganization` plus tests
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBOrganization
* Set up GitHub Pages (for Storybook)

# Acceptance Criteria:

- [x] A form called `UCSBOrganizationForm` is visible in the storybook
      accessible on the Github Pages link.

- [x] The form has all the fields that are in the database table 
      the form fields are labelled with user-friendly names corresponding
      to the database table column names.

- [x] The form has suitable validations for all fields, indicating which fields
      are required to be non-blank, and any validation that should be performed
      (e.g. on dates, time values, numeric values with restricted ranges etc.).
      You can use regular expressions for this, or any of the other validations
      features of `react-query-form`, using the `register` feature, documented here:
      <https://www.react-hook-form.com/api/useform/register/>.  Consult
      both the `RestaurantForm.js` and `UCSBDatesForm.js` files for examples.

- [x] If there are date/time fields, use a date/time picker similar
      to the one in the `UCSBDatesForm` component.  (If this is
      not applicable to your table, then you can skip this step.)

- [x] The `UCSBOrganizationForm.stories.js` file should have at least one story 
      for a create scenario, and another for an update scenario.
      
- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new form (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR.

# Implementation Details:

- [x] Under `frontend/src/main/components/UCSBOrganization/` there is a file
      called `UCSBOrganizationForm` modelled after 
      the files `RestaurantForm.js` and/or `UCSBDatesForm.js`

- [x] Change the form fields so that they correspond to 
      the form fields of your database record.  If there are 
      are labelled with user-friendly names corresponding
      to the database table column names.

- [x] Add suitable validations for all of your fields indicating which fields
      are required to be non-blank, and any validation that should be performed
      (e.g. on dates, time values, numeric values with restricted ranges etc.).
      You can use regular expressions for this, or any of the other validations
      features of `react-query-form`, using the `register` feature, documented here:
      <https://www.react-hook-form.com/api/useform/register/>. 
      Consult both the `Restaurant` and `UCSBDates` examples for guidance.

- [x] The form should take a prop called `initialContents` which is either 
      undefined, or an object that has the same fields as the database table.
      When passed, it indicates that the form is being used to edit an existing
      object.  The `id` field should be displayed as a read-only field,
      and the other fields are pre-populated with the values from the object.

- [x] When the `initialContents` is undefined, it indicates that the form is
      being used to create a new object.  Therefore, if the id field is autogenerated,
      it should not be displayed on the form, and other form values should 
      be either empty, or populated with default or example values (as appropriate).
      
- [x] The form should take prop called `submitAction` which is passed to the
      `handleSubmit` function returned by `useForm`, as in the examples
      `RestaurantForm.js` and `UCSBDatesForm.js`

- [x] The form should take a prop called `buttonLabel` with a default value
      of `Create`.  The value of this prop is used as the label for the button
      as shown in  `RestaurantForm.js` and `UCSBDatesForm.js`.            

- [x] Under `frontend/src/test/components/UCSBOrganization/` create a file called `UCSBOrganizationForm.test.js` modelled after the files `RestaurantForm.test.js` and `UCSBDatesForm.test.js`.

- [x] Under `frontend/src/stories/components/UCSBOrganization/` create a file called `UCSBOrganizationForm.stories.js` modelled after the files `RestaurantForm.stories.js` and `UCSBDatesForm.stories.js`.
      
# Notes

* For *this* issue, it is not necessary that the form be linked to a
  page that connects it to the backend; that will be done in a later issue.

* This issue illustrates how it is possible to create at least part of the frontend
  for a feature even if/when the backend is not yet complete.

* It also illustrates how we can create a component that can be reused, in this
  case for both creating and editing a database record.

Reminders (all from `frontend` directory):
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/UCSBOrganization/UCSBOrganizationForm.js`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the issue "Table Component for `UCSBOrganization` plus tests"
following all the usual steps (assign to self, drag to "In Progress", start new branch.)

### LINKED ISSUE #20: Table Component for `UCSBOrganization` plus tests
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBOrganization
* Set up GitHub Pages (for Storybook)

# Acceptance Criteria:

- [x] A table called `UCSBOrganizationTable` is visible in the storybook
      accessible on the Github Pages link.
      
- [x] The table has all the fields that are in the database table 
      labelled with user-friendly names corresponding to the database table column names.

- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new table (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `UCSBOrganizationTable` component.

# Implementation Details

- [x] Under `frontend/src/main/components/UCSBOrganization/` create a file called `UCSBOrganizationTable`,
      modelled after the files `RestaurantTable.js` and `UCSBDatesTable.js`

- [x] Under `frontend/src/test/components/UCSBOrganization/` create a file called `UCSBOrganizationTable.test.js` 
      modelled after the files `RestaurantTable.test.js and `UCSBDatesTable.test.js`.

- [x] Under `frontend/src/stories/components/UCSBOrganization/` create a file called `UCSBOrganizationTable.stories.js`,
      modelled after the files `RestaurantTable.stories.js` and `UCSBDatesTable.stories.js`.
        
# Notes

* For *this* issue, tt is not necessary that the table be linked to a
  page that connects it to the backend; that will be done in a later issue.

* This issue illustrates how it is possible to create at least part of the frontend
  for a feature even if/when the backend is not yet complete.

# Reminders (all from `frontend` directory):

* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/UCSBOrganization/UCSBOrganizationForm.js`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the issue "Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js"

Follow all the usual steps (assign to self, drag to "In Progress", start new branch.)

### LINKED ISSUE #21: Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js
# Dependencies

None: can be done in parallel with other issues

# Discussion

In this issue, you'll set up placeholders for the three pages you are adding to the app.  

These placeholder components are temporary, but they are necessary so that you can 
add routes to the pages in `frontend/src/App.js` and add a link to the `/ucsborganization` 
name in to the Navigation Bar of the app in `frontend/src/components/AppNavbar.js`.

Note that the contents of the placeholder pages and tests are temporary, 
and will be replaced in a later issue.  However, the changes you make in `App.js`
and `AppNavbar.js` will be permanent.

The reason for the placeholder code is that we can't really test the
changes to `App.js` and `AppNavbar.js` until at least some placeholder 
component for the pages exists, and we can't really test the new pages unless they 
are routed to in the app.  The placeholder solves this ["chicken/egg" problem](https://en.wikipedia.org/wiki/Chicken_or_the_egg).

# Acceptance Criteria

- [x] On the main navigation bar, there is a link to `UCSBOrganization`
      that takes the user to the `UCSBOrganizationIndexPage` page (a placeholder for now) 
      at the url `/ucsborganization`.
- [x] The `UCSBOrganizationIndexPage` page has a link to the `UCSBOrganizationCreatePage` page 
      at the url `/ucsborganization/create`.
- [x] The `UCSBOrganizationIndexPage` page has a link to the `UCSBOrganizationEditPage` page 
      at the url `/ucsborganization/edit/1`.

# Implementation Steps    
 
- [x] Under `frontend/src/main/pages/UCSBOrganization/` create three files
      called `UCSBOrganizationCreatePage.js`, `UCSBOrganizationEditPage.js`, `UCSBOrganizationIndexPage.js`, modelled after 
      `PlaceholderCreatePage.js`, `PlaceholderEditPage.js`, `PlaceholderIndexPage.js`.
      The only change that should be needed is the name of the component
      (see "Notes" below)
      
- [x] Under `frontend/src/tests/pages/UCSBOrganization/` create three files called `UCSBOrganizationCreatePage.test.js`, `UCSBOrganizationEditPage.test.js`, `UCSBOrganizationIndexPage.test.js`  modelled after `PlaceholderCreatePage.test.js`, `PlaceholderEditPage.test.js`, `PlaceholderIndexPage.test.js`. The only change that should be needed is the name of the component 
      being imported.

- [x] In `frontend/src/App.js`, there is a section of code that establishes the routes to the pages for the `UCSBOrganization` components that looks similar to the ones for `Restaurants`, `UCSBDates`, and the `Placeholder`.  Copy/paste this code, changing, `Restaurant` to  `UCSBOrganization`, and `/restaurants` to `/ucsborganization` 
      
- [x] In `frontend/src/main/components/Nav/AppNavbar.js`,add a section of code that establishes the navbar link for `UCSBOrganization`.  It should look similar to this code that establishes the link for `Restaurants`. Copy/paste this code, changing `/restaurants` to  `/ucsborganization`, and `Restaurants` to `UCSBOrganization`
     
- [x] Fire up the app on localhost and make sure that you can navigate to the pages for UCSBOrganization.  You should see pages similar to the ones at the `Placeholder` link on the navbar.

# Notes

The changes you will need to make from the examples are minimal.

In the three page components, typically you will only need to change the 
name of the default export, changing `Placeholder` to `UCSBOrganization`

```js
export default function PlaceholderCreatePage() {
```

In `App.js`, you will need to:
* Add import statements for the three page components
* Copy/paste the section of code below, changing `/restaurants`  to `/ucsborganization` and `Restaurant` to `UCSBOrganization`
                     
```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Route exact path="/restaurants" element={<RestaurantIndexPage />} />
        </>
      )
}
{
      hasRole(currentUser, "ROLE_ADMIN") && (
        <>
          <Route exact path="/restaurants/edit/:id" element={<RestaurantEditPage />} />
          <Route exact path="/restaurants/create" element={<RestaurantCreatePage />} />
        </>
      )
}
```

In `AppNavbar.js`, copy/paste this section of code, and change  `/restaurants` to `/ucsborganization` and `Restaurants` to `UCSBOrganization`:

```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Nav.Link as={NavLink} to="/restaurants">Restaurants</Nav.Link>
        </>
      )
}
```
# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/Nav/AppNavbar.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Create Page for `UCSBOrganization` plus tests and stories" (following the usual steps for a new issue)

### LINKED ISSUE #22: Create Page for `UCSBOrganization` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBOrganization
* Form Component for UCSBOrganization
* Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [x] When you navigate to `/ucsborganization/create` in the URL bar, 
      there is page that allows the user to create a new UCSBOrganization record.

- [x] When you enter data into the form and click the submit button,
      if the data is valid, the data is sent to the server, 
      a new UCSBOrganization record is created,and the user is routed to the 
      `/ucsborganization` route for the `UCSBOrganizationIndexPage` page.

- [x] When you enter data into the form and click the submit button,
      if the data is not valid,appropriate error messages are displayed, 
      the data is NOT sent to the server, a new UCSBOrganization record is NOT created,
      and the user remains on the `ucsborganization/create` page.

- [x] When you submit valid data to the page and click submit, a new valid database
      entry is stored in the database.  (You can verify this by using the swagger
      endpoint to view the current data in the table.)

- [x] The PR description has step-by-step descriptions for testing the new page, along
      with screenshots, so that someone reviewing the PR will know what to do to test
      it, and what it is supposed to look like when it functions correctly.

- [x] The PR description has a link to the storybook entry for the new page.

# Implementation Details

- [x] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `UCSBOrganization` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `UCSBOrganization`, but not identical.  You will need
      to know the exact name of the API endpoints for `UCSBOrganization` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [x] In `UCSBOrganizationCreatePage.js`, replace the code from `PlaceholderCreatePage.js` 
      with code modelled after the files `RestaurantCreatePage.js` and/or `UCSBDatesCreatePage.js`
      that is appropriate to your `UCSBOrganization` table. Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] In `UCSBOrganizationCreatePage.test.js`, replace the code from `PlaceholderCreatePage.test.js` 
      with code modelled after  the files `RestaurantCreatePage.test.js` and/or `UCSBDatesCreatePage.test.js`
      appropriate to your `UCSBOrganization` table.  Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] Under `frontend/src/stories/pages/UCSBOrganization/` create a file called `UCSBOrganizationCreatePage.stories.js` 
      modelled after the files `RestaurantCreatePage.stories.js` and/or `UCSBDatesCreatePage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/UCSBOrganization/UCSBOrganizationCreatePage.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Index Page for `UCSBOrganization` plus tests and stories"(following the usual steps for a new issue)

### LINKED ISSUE #23: Index Page for `UCSBOrganization` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBOrganization
* Table Component for UCSBOrganization 
* Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [x] When the user navigates to `/ucsborganization` the page will be populated
      with data all rows in the database, and the user will be able to see
      all of the data in the table.

- [x] When the index page is accessed by an admin user, they will be able to
      see a button to create a new record, and a button to edit each record,
      and a button to delete each record.

- [x] When the index page is accessed by an regular logged in user, 
      the buttons to create a new record, edit a record, and delete a record
      will not be visible in the table.  Logged in users will be able to see
      the data in the table, but that is all.

- [x] When the index page is accessed by an admin user, the edit button will
      navigate to the URL for the edit page for that record.  (The page should display
      if the issue to implement it is already completed, or a blank page with the correct
      URL if it is not.)

- [x] When the index page is accessed by an admin user, the delete button will
      call the endpoint to delete the record from the database, and then refresh
      the page.  The refreshed page will not show the deleted record.

- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new page (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `UCSBOrganizationIndexPage` component.

# Implementation Details

- [x] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `UCSBOrganization` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `UCSBOrganization`, but not identical.  You will need
      to know the exact name of the API endpoints for `UCSBOrganization` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [x] Modify the `UCSBOrganizationIndexPage`, replacing the placeholder
      content with content modelled after the files `RestaurantIndexPage.js`
      and/or `UCSBDatesIndexPage.js`.  Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] Modify `UCSBOrganizationIndexPage.test.js`  replacing the placeholder
      content with content modelled after the files `RestaurantIndexPage.test.js`
      and/or `UCSBDatesIndexPage.test.js`. Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] Under `frontend/src/stories/pages/UCSBOrganization/` create a file
      called `UCSBOrganizationIndexPage.stories.js` modelled after 
      the files `RestaurantIndexPage.stories.js` and `UCSBDatesIndexPage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/UCSBOrganization/UCSBOrganizationIndexPage.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Edit Page for `UCSBOrganization` plus tests and stories" (following the usual steps for a new issue)

### LINKED ISSUE #24: Edit Page for `UCSBOrganization` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBOrganization
* Form Component for UCSBOrganization  
* Copy Placeholders for `UCSBOrganization` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [x] When the user navigates to `/ucsborganization/edit/:id` where `:id` 
      is the `id` field of a valid record in the table, the page will be populated
      with data from that row of the database, and will be able to edit fields
      from that database record.

- [x] Valid changes made on the page are saved to the database when the user clicks
      the submit button.
- [x] Changes made on the page are NOT saved when the page contains invalid data; instead,
      appropriate error messages are shown.
- [x] Changes made on the page are NOT saved when the user clicks the cancel button,
      and the user is routed back to the previous page they were on (like the "back button").     

- [x] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new page (since this is a frontend change).

- [x] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `UCSBOrganizationEditPage` component.

# Implementation Details

- [x] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `UCSBOrganization` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `UCSBOrganization`, but not identical.  You will need
      to know the exact name of the API endpoints for `UCSBOrganization` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [x] Replace the placeholder content in `UCSBOrganizationEditPage.js`
      with appropriate content from `RestaurantEditPage.js` and/or
      `UCSBDatesEditPage.js`. Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] Replace the placeholder content in `UCSBOrganizationEditPage.test.js`
      with appropriate content from `RestaurantEditPage.test.js` and/or
      `UCSBDatesEditPage.test.js`. Be sure to get the API endpoint names correct for your `UCSBOrganization` table.

- [x] Under `frontend/src/stories/pages/UCSBOrganization/` create a file
      called `UCSBOrganizationEditPage.stories.js` modelled after 
      the files `RestaurantEditPage.stories.js` and/or `UCSBDatesEditPage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/UCSBOrganization/UCSBOrganizationEditPage.js`

# What to do next

When you are done with this issue, you are finished with the frontend CRUD
operations for `UCSBOrganization`.  Now, please give your full attention to 
helping others on your team to complete the sprint, so that the team
is ready to submit on Canvas by the deadline.

### PR DESCRIPTION
**Pull request by gretchenlam**
In this PR, I implemented UCSBOrganization form and table components, which can be seen in storybook, and their tests. I also implemented UCSBOrganization Create, Edit, Index pages, and their tests.

100% coverage and mutation tests:
PNG image
PNG image

Dokku dev deployment: https://team03-gretchenlam-dev.dokku-13.cs.ucsb.edu/

Storybook: https://ucsb-cs156-w24.github.io/team03-w24-7pm-1/prs/77/storybook/?path=/story/components-ucsborganization-ucsborganizationform--create

Closes #19 
Closes #20
Closes #21
Closes #22
Closes #23
Closes #24

### CODE REVIEW

**Comment by Daoyijiucsb** [comment]
It works on Dokku, but the form appears different from the [original webpage](https://team03.dokku-00.cs.ucsb.edu/ucsborganization/create).

I'm unsure whether we need to replicate it exactly as the original. The original webpage also controls error messages in the inactive column, displaying messages like 'The input should be either true or false' when I input something incorrect. This can be easily fixed by adding regex in the UCSBOrganizationForm.js file.

**Comment by gretchenlam** [comment]
> It works on Dokku, but the form appears different from the [original webpage](https://team03.dokku-00.cs.ucsb.edu/ucsborganization/create).
> 
> I'm unsure whether we need to replicate it exactly as the original. The original webpage also controls error messages in the inactive column, displaying messages like 'The input should be either true or false' when I input something incorrect. This can be easily fixed by adding regex in the UCSBOrganizationForm.js file.

Thank you for catching that! I added validation tests for inactive. As for replicating it exactly, I can ask the TA's later today to see if we need to do that. I just modeled my index page / table after the Restaurants files.

**Comment by Daoyijiucsb** [comment]
Thanks for dealing with it. 
LGTM! All feature are included .

**Comment by Ze-el** [comment]
Could you include the storybook link of this PR as mentioned in the acceptance criteria? Also this branch seems to have a merge conflict with main.

**Review by owenjpark — APPROVED** [review]
LGTM! Works as expected on dokku with all features.

**Comment by gretchenlam** [comment]
> Could you include the storybook link of this PR as mentioned in the acceptance criteria? Also this branch seems to have a merge conflict with main.

Resolved merge conflict! And storybook link included now. Thanks for the catch!

**Review by liamlizard — COMMENTED** [review]
Looks pretty good. On Dokku while trying to edit the Organizations it was giving me a 404 error, here is an image. As all the tests pass, its weird its not working but I also checked the example deployment and I get the same behavior. So I don't think there's anything we can do but I wanted to leave a comment about it and get a consensus before merging. 

Screenshot 2024-02-19 at 12 57 15 PM

**Pull request merged**
