### PR TITLE
Create, Edit, Index Pages for HelpRequest plus tests and stories 

### LINKED ISSUE #44: Copy files for Backend CRUD API `HelpRequest` from team02
# Dependencies

Do the "Create personal dokku dev deployment" issue first.

# Acceptance Criteria:

- [ ] Backend API routes for CRUD operations for `HelpRequest` are
      available in Swagger (following the criteria from team02)

# Implementation Details:
- [ ] Find `HelpRequest.java` in your team02 project in the directory 
      `src/main/java/edu/ucsb/cs156/example/entities` 
      and copy it into your team03 project in the same directory.
- [ ] Do the same for  `HelpRequestRepository.java` from the directory
      `src/main/java/edu/ucsb/cs156/example/repositorires`
- [ ] Do the same for `HelpRequestController.java` from the directory
      `src/main/java/edu/ucsb/cs156/example/controllers`
- [ ] Do the same for `HelpRequestControllerTests.java` from the directory
      `src/test/java/edu/ucsb/cs156/example/controllers`          
- [ ] With these files in place, visit swagger and make sure 
      the CRUD operations for `HelpRequest` are working properly.

# What to do next

** Make a PR**: When you've met all of the acceptance criteria, do a PR for this branch,
being sure to enter a [reasonable title](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-titles)
and [description](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-descriptions).

In the description, include the text "Closes #n" where `n` is the number of
this issue.

Then ask for a team member to review your PR.

Finally: drag this issue from "In Progress" to "In Review".

** Review Others' PRs**: Next, see if there are any PRs that need to be code reviewed and merged.  Unless you are the
first person on your team to complete a PR, there likely is at least one.
See: 
* [General Code Review Advice](https://ucsb-cs156.github.io/topics/code_reviews/)
* [Performin Code Reviews on Github](https://ucsb-cs156.github.io/topics/code_reviews/code_reviews_github.html)

** Start your next issue **: Then, find the issue for "Create fixtures for `HelpRequest`" on the Kanban board in the ToDo column.

* Assign it to yourself
* Drag into "In Progress"
* Create a new branch, starting from the branch for the issue you just finished.
* Start on the new issue.

### LINKED ISSUE #45: Create fixtures for `HelpRequest`
# Dependencies

None; this issue should be done first before other issues for the
HelpRequest table

# Acceptance Criteria:

- [ ] In the frontend directory `frontend/src/main/fixtures` there is a file called 
      `helpRequestFixtures.js` that contains Javascript fixtures
      for the database table that is similar to the `restaurantFixtures.js` 
      and `ucsbDatesFixtures.js` files in the same directory.
- [ ] Each example should correspond to the JSON format of an object returned by 
      the GET API endpoint from team02 for the `HelpRequest` database table object.

# What to do next

** Make a PR**: When you've met all of the acceptance criteria, do a PR for this branch,
being sure to enter a [reasonable title](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-titles)
and [description](https://ucsb-cs156.github.io/topics/pull_requests.html#pr-descriptions).

In the description, include the text "Closes #n" where `n` is the number of
this issue.

Then ask for a team member to review your PR, and drag this issue from "In Progress" to "In Review".

** Review Others' PRs**: Next, see if there are any PRs that need to be code reviewed and merged.  Unless you are the
first person on your team to complete a PR, there likely is at least one.
See: 
* [General Code Review Advice](https://ucsb-cs156.github.io/topics/code_reviews/)
* [Performin Code Reviews on Github](https://ucsb-cs156.github.io/topics/code_reviews/code_reviews_github.html)

** Start your next issue **: Then, find the issue for "Form Component for `HelpRequest` plus tests" on the Kanban board in the ToDo column.

* Assign it to yourself
* Drag into "In Progress"
* Create a new branch, starting from the branch for the issue you just finished.
* Start on the new issue.

### LINKED ISSUE #46: Form Component for `HelpRequest` plus tests
# Dependencies

Complete the following issues first:
* Create fixtures for HelpRequest
* Set up GitHub Pages (for Storybook)

# Acceptance Criteria:

- [ ] A form called `HelpRequestForm` is visible in the storybook
      accessible on the Github Pages link.

- [ ] The form has all the fields that are in the database table 
      the form fields are labelled with user-friendly names corresponding
      to the database table column names.

- [ ] The form has suitable validations for all fields, indicating which fields
      are required to be non-blank, and any validation that should be performed
      (e.g. on dates, time values, numeric values with restricted ranges etc.).
      You can use regular expressions for this, or any of the other validations
      features of `react-query-form`, using the `register` feature, documented here:
      <https://www.react-hook-form.com/api/useform/register/>.  Consult
      both the `RestaurantForm.js` and `UCSBDatesForm.js` files for examples.

- [ ] If there are date/time fields, use a date/time picker similar
      to the one in the `UCSBDatesForm` component.  (If this is
      not applicable to your table, then you can skip this step.)

- [ ] The `HelpRequestForm.stories.js` file should have at least one story 
      for a create scenario, and another for an update scenario.
      
- [ ] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new form (since this is a frontend change).

- [ ] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR.

# Implementation Details:

- [x] Under `frontend/src/main/components/HelpRequest/` there is a file
      called `HelpRequestForm` modelled after 
      the files `RestaurantForm.js` and/or `UCSBDatesForm.js`

- [x] Change the form fields so that they correspond to 
      the form fields of your database record.  If there are 
      are labelled with user-friendly names corresponding
      to the database table column names.

- [x] Add suitable validations for all of your fields indicating which fields
      are required to be non-blank, and any validation that should be performed
      (e.g. on dates, time values, numeric values with restricted ranges etc.).
      You can use regular expressions for this, or any of the other validations
      features of `react-query-form`, using the `register` feature, documented here:
      <https://www.react-hook-form.com/api/useform/register/>. 
      Consult both the `Restaurant` and `UCSBDates` examples for guidance.

- [x] The form should take a prop called `initialContents` which is either 
      undefined, or an object that has the same fields as the database table.
      When passed, it indicates that the form is being used to edit an existing
      object.  The `id` field should be displayed as a read-only field,
      and the other fields are pre-populated with the values from the object.

- [x] When the `initialContents` is undefined, it indicates that the form is
      being used to create a new object.  Therefore, if the id field is autogenerated,
      it should not be displayed on the form, and other form values should 
      be either empty, or populated with default or example values (as appropriate).
      
- [x] The form should take prop called `submitAction` which is passed to the
      `handleSubmit` function returned by `useForm`, as in the examples
      `RestaurantForm.js` and `UCSBDatesForm.js`

- [x] The form should take a prop called `buttonLabel` with a default value
      of `Create`.  The value of this prop is used as the label for the button
      as shown in  `RestaurantForm.js` and `UCSBDatesForm.js`.            

- [x] Under `frontend/src/test/components/HelpRequest/` create a file called `HelpRequestForm.test.js` modelled after the files `RestaurantForm.test.js` and `UCSBDatesForm.test.js`.

- [x] Under `frontend/src/stories/components/HelpRequest/` create a file called `HelpRequestForm.stories.js` modelled after the files `RestaurantForm.stories.js` and `UCSBDatesForm.stories.js`.
      
# Notes

* For *this* issue, it is not necessary that the form be linked to a
  page that connects it to the backend; that will be done in a later issue.

* This issue illustrates how it is possible to create at least part of the frontend
  for a feature even if/when the backend is not yet complete.

* It also illustrates how we can create a component that can be reused, in this
  case for both creating and editing a database record.

Reminders (all from `frontend` directory):
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/HelpRequest/HelpRequestForm.js`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the issue "Table Component for `HelpRequest` plus tests"
following all the usual steps (assign to self, drag to "In Progress", start new branch.)

### LINKED ISSUE #47: Table Component for `HelpRequest` plus tests
# Dependencies

Complete the following issues first:
* Create fixtures for HelpRequest
* Set up GitHub Pages (for Storybook)

# Acceptance Criteria:

- [ ] A table called `HelpRequestTable` is visible in the storybook
      accessible on the Github Pages link.
      
- [ ] The table has all the fields that are in the database table 
      labelled with user-friendly names corresponding to the database table column names.

- [ ] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new table (since this is a frontend change).

- [ ] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `HelpRequestTable` component.

# Implementation Details

- [ ] Under `frontend/src/main/components/HelpRequest/` create a file called `HelpRequestTable`,
      modelled after the files `RestaurantTable.js` and `UCSBDatesTable.js`

- [ ] Under `frontend/src/test/components/HelpRequest/` create a file called `HelpRequestTable.test.js` 
      modelled after the files `RestaurantTable.test.js and `UCSBDatesTable.test.js`.

- [ ] Under `frontend/src/stories/components/HelpRequest/` create a file called `HelpRequestTable.stories.js`,
      modelled after the files `RestaurantTable.stories.js` and `UCSBDatesTable.stories.js`.
        
# Notes

* For *this* issue, tt is not necessary that the table be linked to a
  page that connects it to the backend; that will be done in a later issue.

* This issue illustrates how it is possible to create at least part of the frontend
  for a feature even if/when the backend is not yet complete.

# Reminders (all from `frontend` directory):

* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/HelpRequest/HelpRequestForm.js`

# What to do next

Do a PR, following all of the usual steps (title, description, `Closes #n` text,
dragging issue to "In Review", requesting reviewers).

Check to see if any fellow team members PRs need to be reviewed.

Then, assign yourself the issue "Copy Placeholders for `HelpRequest` pages; add to App.js/AppNavbar.js"

Follow all the usual steps (assign to self, drag to "In Progress", start new branch.)

### LINKED ISSUE #48: Copy Placeholders for `HelpRequest` pages; add to App.js/AppNavbar.js
# Dependencies

None: can be done in parallel with other issues

# Discussion

In this issue, you'll set up placeholders for the three pages you are adding to the app.  

These placeholder components are temporary, but they are necessary so that you can 
add routes to the pages in `frontend/src/App.js` and add a link to the `/helprequest` 
name in to the Navigation Bar of the app in `frontend/src/components/AppNavbar.js`.

Note that the contents of the placeholder pages and tests are temporary, 
and will be replaced in a later issue.  However, the changes you make in `App.js`
and `AppNavbar.js` will be permanent.

The reason for the placeholder code is that we can't really test the
changes to `App.js` and `AppNavbar.js` until at least some placeholder 
component for the pages exists, and we can't really test the new pages unless they 
are routed to in the app.  The placeholder solves this ["chicken/egg" problem](https://en.wikipedia.org/wiki/Chicken_or_the_egg).

# Acceptance Criteria

- [ ] On the main navigation bar, there is a link to `HelpRequest`
      that takes the user to the `HelpRequestIndexPage` page (a placeholder for now) 
      at the url `/helprequest`.
- [ ] The `HelpRequestIndexPage` page has a link to the `HelpRequestCreatePage` page 
      at the url `/helprequest/create`.
- [ ] The `HelpRequestIndexPage` page has a link to the `HelpRequestEditPage` page 
      at the url `/helprequest/edit/1`.

# Implementation Steps    
 
- [ ] Under `frontend/src/main/pages/HelpRequest/` create three files
      called `HelpRequestCreatePage.js`, `HelpRequestEditPage.js`, `HelpRequestIndexPage.js`, modelled after 
      `PlaceholderCreatePage.js`, `PlaceholderEditPage.js`, `PlaceholderIndexPage.js`.
      The only change that should be needed is the name of the component
      (see "Notes" below)
      
- [ ] Under `frontend/src/tests/pages/HelpRequest/` create three files called `HelpRequestCreatePage.test.js`, `HelpRequestEditPage.test.js`, `HelpRequestIndexPage.test.js`  modelled after `PlaceholderCreatePage.test.js`, `PlaceholderEditPage.test.js`, `PlaceholderIndexPage.test.js`. The only change that should be needed is the name of the component 
      being imported.

- [ ] In `frontend/src/App.js`, there is a section of code that establishes the routes to the pages for the `HelpRequest` components that looks similar to the ones for `Restaurants`, `UCSBDates`, and the `Placeholder`.  Copy/paste this code, changing, `Restaurant` to  `HelpRequest`, and `/restaurants` to `/helprequest` 
      
- [ ] In `frontend/src/main/components/Nav/AppNavbar.js`,add a section of code that establishes the navbar link for `HelpRequest`.  It should look similar to this code that establishes the link for `Restaurants`. Copy/paste this code, changing `/restaurants` to  `/helprequest`, and `Restaurants` to `HelpRequest`
     
- [ ] Fire up the app on localhost and make sure that you can navigate to the pages for HelpRequest.  You should see pages similar to the ones at the `Placeholder` link on the navbar.

# Notes

The changes you will need to make from the examples are minimal.

In the three page components, typically you will only need to change the 
name of the default export, changing `Placeholder` to `HelpRequest`

```js
export default function PlaceholderCreatePage() {
```

In `App.js`, you will need to:
* Add import statements for the three page components
* Copy/paste the section of code below, changing `/restaurants`  to `/helprequest` and `Restaurant` to `HelpRequest`
                     
```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Route exact path="/restaurants" element={<RestaurantIndexPage />} />
        </>
      )
}
{
      hasRole(currentUser, "ROLE_ADMIN") && (
        <>
          <Route exact path="/restaurants/edit/:id" element={<RestaurantEditPage />} />
          <Route exact path="/restaurants/create" element={<RestaurantCreatePage />} />
        </>
      )
}
```

In `AppNavbar.js`, copy/paste this section of code, and change  `/restaurants` to `/helprequest` and `Restaurants` to `HelpRequest`:

```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Nav.Link as={NavLink} to="/restaurants">Restaurants</Nav.Link>
        </>
      )
}
```
# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/Nav/AppNavbar.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Create Page for `HelpRequest` plus tests and stories" (following the usual steps for a new issue)

### LINKED ISSUE #49: Create Page for `HelpRequest` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for HelpRequest
* Form Component for HelpRequest
* Copy Placeholders for `HelpRequest` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [ ] When you navigate to `/helprequest/create` in the URL bar, 
      there is page that allows the user to create a new HelpRequest record.

- [ ] When you enter data into the form and click the submit button,
      if the data is valid, the data is sent to the server, 
      a new HelpRequest record is created,and the user is routed to the 
      `/helprequest` route for the `HelpRequestIndexPage` page.

- [ ] When you enter data into the form and click the submit button,
      if the data is not valid,appropriate error messages are displayed, 
      the data is NOT sent to the server, a new HelpRequest record is NOT created,
      and the user remains on the `helprequest/create` page.

- [ ] When you submit valid data to the page and click submit, a new valid database
      entry is stored in the database.  (You can verify this by using the swagger
      endpoint to view the current data in the table.)

- [ ] The PR description has step-by-step descriptions for testing the new page, along
      with screenshots, so that someone reviewing the PR will know what to do to test
      it, and what it is supposed to look like when it functions correctly.

- [ ] The PR description has a link to the storybook entry for the new page.

# Implementation Details

- [ ] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `HelpRequest` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `HelpRequest`, but not identical.  You will need
      to know the exact name of the API endpoints for `HelpRequest` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [ ] In `HelpRequestCreatePage.js`, replace the code from `PlaceholderCreatePage.js` 
      with code modelled after the files `RestaurantCreatePage.js` and/or `UCSBDatesCreatePage.js`
      that is appropriate to your `HelpRequest` table. Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] In `HelpRequestCreatePage.test.js`, replace the code from `PlaceholderCreatePage.test.js` 
      with code modelled after  the files `RestaurantCreatePage.test.js` and/or `UCSBDatesCreatePage.test.js`
      appropriate to your `HelpRequest` table.  Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] Under `frontend/src/stories/pages/HelpRequest/` create a file called `HelpRequestCreatePage.stories.js` 
      modelled after the files `RestaurantCreatePage.stories.js` and/or `UCSBDatesCreatePage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/HelpRequest/HelpRequestCreatePage.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Index Page for `HelpRequest` plus tests and stories"(following the usual steps for a new issue)

### LINKED ISSUE #50: Index Page for `HelpRequest` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for HelpRequest
* Table Component for HelpRequest 
* Copy Placeholders for `HelpRequest` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [ ] When the user navigates to `/helprequest` the page will be populated
      with data all rows in the database, and the user will be able to see
      all of the data in the table.

- [ ] When the index page is accessed by an admin user, they will be able to
      see a button to create a new record, and a button to edit each record,
      and a button to delete each record.

- [ ] When the index page is accessed by an regular logged in user, 
      the buttons to create a new record, edit a record, and delete a record
      will not be visible in the table.  Logged in users will be able to see
      the data in the table, but that is all.

- [ ] When the index page is accessed by an admin user, the edit button will
      navigate to the URL for the edit page for that record.  (The page should display
      if the issue to implement it is already completed, or a blank page with the correct
      URL if it is not.)

- [ ] When the index page is accessed by an admin user, the delete button will
      call the endpoint to delete the record from the database, and then refresh
      the page.  The refreshed page will not show the deleted record.

- [ ] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new page (since this is a frontend change).

- [ ] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `HelpRequestIndexPage` component.

# Implementation Details

- [ ] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `HelpRequest` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `HelpRequest`, but not identical.  You will need
      to know the exact name of the API endpoints for `HelpRequest` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [ ] Modify the `HelpRequestIndexPage`, replacing the placeholder
      content with content modelled after the files `RestaurantIndexPage.js`
      and/or `UCSBDatesIndexPage.js`.  Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] Modify `HelpRequestIndexPage.test.js`  replacing the placeholder
      content with content modelled after the files `RestaurantIndexPage.test.js`
      and/or `UCSBDatesIndexPage.test.js`. Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] Under `frontend/src/stories/pages/HelpRequest/` create a file
      called `HelpRequestIndexPage.stories.js` modelled after 
      the files `RestaurantIndexPage.stories.js` and `UCSBDatesIndexPage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/HelpRequest/HelpRequestIndexPage.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Edit Page for `HelpRequest` plus tests and stories" (following the usual steps for a new issue)

### LINKED ISSUE #51: Edit Page for `HelpRequest` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for HelpRequest
* Form Component for HelpRequest  
* Copy Placeholders for `HelpRequest` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [ ] When the user navigates to `/helprequest/edit/:id` where `:id` 
      is the `id` field of a valid record in the table, the page will be populated
      with data from that row of the database, and will be able to edit fields
      from that database record.

- [ ] Valid changes made on the page are saved to the database when the user clicks
      the submit button.
- [ ] Changes made on the page are NOT saved when the page contains invalid data; instead,
      appropriate error messages are shown.
- [ ] Changes made on the page are NOT saved when the user clicks the cancel button,
      and the user is routed back to the previous page they were on (like the "back button").     

- [ ] The PR description where the code addressing this issue is submitted contains
      a screenshot of the new page (since this is a frontend change).

- [ ] The PR description where the code addressing this issue is submitted contains
      a link to the published storybook for the PR, linking directly to the story 
      for the new `HelpRequestEditPage` component.

# Implementation Details

- [ ] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `HelpRequest` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `HelpRequest`, but not identical.  You will need
      to know the exact name of the API endpoints for `HelpRequest` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [ ] Replace the placeholder content in `HelpRequestEditPage.js`
      with appropriate content from `RestaurantEditPage.js` and/or
      `UCSBDatesEditPage.js`. Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] Replace the placeholder content in `HelpRequestEditPage.test.js`
      with appropriate content from `RestaurantEditPage.test.js` and/or
      `UCSBDatesEditPage.test.js`. Be sure to get the API endpoint names correct for your `HelpRequest` table.

- [ ] Under `frontend/src/stories/pages/HelpRequest/` create a file
      called `HelpRequestEditPage.stories.js` modelled after 
      the files `RestaurantEditPage.stories.js` and/or `UCSBDatesEditPage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/HelpRequest/HelpRequestEditPage.js`

# What to do next

When you are done with this issue, you are finished with the frontend CRUD
operations for `HelpRequest`.  Now, please give your full attention to 
helping others on your team to complete the sprint, so that the team
is ready to submit on Canvas by the deadline.

### PR DESCRIPTION
**Pull request by Daoyijiucsb**
I finished a team03. 
It contains Create, Edit, Index Pages for HelpRequest.

check from here: 
https://team03-daoyi-dev.dokku-13.cs.ucsb.edu
storybook link:
https://ucsb-cs156-w24.github.io/team03-w24-7pm-1/prs/75/storybook/?path=/story/components-helprequest-helprequestform--create

Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/44
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/45
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/46
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/47
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/48
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/49
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/50
Closes https://github.com/ucsb-cs156-w24/team03-w24-7pm-1/issues/51

### CODE REVIEW

**Review by gretchenlam — APPROVED** [review]
LGTM! dokku dev deployment works as expected

**Comment by Ze-el** [comment]
Include the published storybook for the PR as mentioned in the acceptance criteria.

**Comment by Daoyijiucsb** [comment]
I added a storybook link!

**Review by Ze-el — APPROVED** [review]
LGTM now!

**Pull request merged**
