### PR TITLE
OP - Copy Placeholders for UCSBDiningCommonsMenuItem pages; add to App.js/AppNavbar.js

### LINKED ISSUE #12: Copy Placeholders for `UCSBDiningCommonsMenuItem` pages; add to App.js/AppNavbar.js
# Dependencies

None: can be done in parallel with other issues

# Discussion

In this issue, you'll set up placeholders for the three pages you are adding to the app.  

These placeholder components are temporary, but they are necessary so that you can 
add routes to the pages in `frontend/src/App.js` and add a link to the `/diningcommonsmenuitem` 
name in to the Navigation Bar of the app in `frontend/src/components/AppNavbar.js`.

Note that the contents of the placeholder pages and tests are temporary, 
and will be replaced in a later issue.  However, the changes you make in `App.js`
and `AppNavbar.js` will be permanent.

The reason for the placeholder code is that we can't really test the
changes to `App.js` and `AppNavbar.js` until at least some placeholder 
component for the pages exists, and we can't really test the new pages unless they 
are routed to in the app.  The placeholder solves this ["chicken/egg" problem](https://en.wikipedia.org/wiki/Chicken_or_the_egg).

# Acceptance Criteria

- [x] On the main navigation bar, there is a link to `UCSBDiningCommonsMenuItem`
      that takes the user to the `UCSBDiningCommonsMenuItemIndexPage` page (a placeholder for now) 
      at the url `/diningcommonsmenuitem`.
- [x] The `UCSBDiningCommonsMenuItemIndexPage` page has a link to the `UCSBDiningCommonsMenuItemCreatePage` page 
      at the url `/diningcommonsmenuitem/create`.
- [x] The `UCSBDiningCommonsMenuItemIndexPage` page has a link to the `UCSBDiningCommonsMenuItemEditPage` page 
      at the url `/diningcommonsmenuitem/edit/1`.

# Implementation Steps    
 
- [x] Under `frontend/src/main/pages/UCSBDiningCommonsMenuItem/` create three files
      called `UCSBDiningCommonsMenuItemCreatePage.js`, `UCSBDiningCommonsMenuItemEditPage.js`, `UCSBDiningCommonsMenuItemIndexPage.js`, modelled after 
      `PlaceholderCreatePage.js`, `PlaceholderEditPage.js`, `PlaceholderIndexPage.js`.
      The only change that should be needed is the name of the component
      (see "Notes" below)
      
- [x] Under `frontend/src/tests/pages/UCSBDiningCommonsMenuItem/` create three files called `UCSBDiningCommonsMenuItemCreatePage.test.js`, `UCSBDiningCommonsMenuItemEditPage.test.js`, `UCSBDiningCommonsMenuItemIndexPage.test.js`  modelled after `PlaceholderCreatePage.test.js`, `PlaceholderEditPage.test.js`, `PlaceholderIndexPage.test.js`. The only change that should be needed is the name of the component 
      being imported.

- [x] In `frontend/src/App.js`, there is a section of code that establishes the routes to the pages for the `UCSBDiningCommonsMenuItem` components that looks similar to the ones for `Restaurants`, `UCSBDates`, and the `Placeholder`.  Copy/paste this code, changing, `Restaurant` to  `UCSBDiningCommonsMenuItem`, and `/restaurants` to `/diningcommonsmenuitem` 
      
- [ ] In `frontend/src/main/components/Nav/AppNavbar.js`,add a section of code that establishes the navbar link for `UCSBDiningCommonsMenuItem`.  It should look similar to this code that establishes the link for `Restaurants`. Copy/paste this code, changing `/restaurants` to  `/diningcommonsmenuitem`, and `Restaurants` to `UCSBDiningCommonsMenuItem`
     
- [ ] Fire up the app on localhost and make sure that you can navigate to the pages for UCSBDiningCommonsMenuItem.  You should see pages similar to the ones at the `Placeholder` link on the navbar.

# Notes

The changes you will need to make from the examples are minimal.

In the three page components, typically you will only need to change the 
name of the default export, changing `Placeholder` to `UCSBDiningCommonsMenuItem`

```js
export default function PlaceholderCreatePage() {
```

In `App.js`, you will need to:
* Add import statements for the three page components
* Copy/paste the section of code below, changing `/restaurants`  to `/diningcommonsmenuitem` and `Restaurant` to `UCSBDiningCommonsMenuItem`
                     
```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Route exact path="/restaurants" element={<RestaurantIndexPage />} />
        </>
      )
}
{
      hasRole(currentUser, "ROLE_ADMIN") && (
        <>
          <Route exact path="/restaurants/edit/:id" element={<RestaurantEditPage />} />
          <Route exact path="/restaurants/create" element={<RestaurantCreatePage />} />
        </>
      )
}
```

In `AppNavbar.js`, copy/paste this section of code, and change  `/restaurants` to `/diningcommonsmenuitem` and `Restaurants` to `UCSBDiningCommonsMenuItem`:

```js
{
      hasRole(currentUser, "ROLE_USER") && (
        <>
          <Nav.Link as={NavLink} to="/restaurants">Restaurants</Nav.Link>
        </>
      )
}
```
# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/components/Nav/AppNavbar.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Create Page for `UCSBDiningCommonsMenuItem` plus tests and stories" (following the usual steps for a new issue)

### LINKED ISSUE #13: Create Page for `UCSBDiningCommonsMenuItem` plus tests and stories
# Dependencies

Complete the following issues first:
* Create fixtures for UCSBDiningCommonsMenuItem
* Form Component for UCSBDiningCommonsMenuItem
* Copy Placeholders for `UCSBDiningCommonsMenuItem` pages; add to App.js/AppNavbar.js

# Acceptance Criteria:

- [x] When you navigate to `/diningcommonsmenuitem/create` in the URL bar, 
      there is page that allows the user to create a new UCSBDiningCommonsMenuItem record.

- [x] When you enter data into the form and click the submit button,
      if the data is valid, the data is sent to the server, 
      a new UCSBDiningCommonsMenuItem record is created,and the user is routed to the 
      `/diningcommonsmenuitem` route for the `UCSBDiningCommonsMenuItemIndexPage` page.

- [x] When you enter data into the form and click the submit button,
      if the data is not valid,appropriate error messages are displayed, 
      the data is NOT sent to the server, a new UCSBDiningCommonsMenuItem record is NOT created,
      and the user remains on the `diningcommonsmenuitem/create` page.

- [x] When you submit valid data to the page and click submit, a new valid database
      entry is stored in the database.  (You can verify this by using the swagger
      endpoint to view the current data in the table.)

- [x] The PR description has step-by-step descriptions for testing the new page, along
      with screenshots, so that someone reviewing the PR will know what to do to test
      it, and what it is supposed to look like when it functions correctly.

- [x] The PR description has a link to the storybook entry for the new page.

# Implementation Details

- [ ] Before starting, refamiliarize yourself with the backend CRUD API endpoints for 
      `UCSBDiningCommonsMenuItem` by looking at the swagger page.  You are going to be copy/pasting
      code from the `Restaurant` and `UCSBDates` components. Those use backend api endpoints
      that are similar to the ones for `UCSBDiningCommonsMenuItem`, but not identical.  You will need
      to know the exact name of the API endpoints for `UCSBDiningCommonsMenuItem` in order to
      be sure that your frontend code is calling the correct backend endpoints.

- [ ] In `UCSBDiningCommonsMenuItemCreatePage.js`, replace the code from `PlaceholderCreatePage.js` 
      with code modelled after the files `RestaurantCreatePage.js` and/or `UCSBDatesCreatePage.js`
      that is appropriate to your `UCSBDiningCommonsMenuItem` table. Be sure to get the API endpoint names correct for your `UCSBDiningCommonsMenuItem` table.

- [ ] In `UCSBDiningCommonsMenuItemCreatePage.test.js`, replace the code from `PlaceholderCreatePage.test.js` 
      with code modelled after  the files `RestaurantCreatePage.test.js` and/or `UCSBDatesCreatePage.test.js`
      appropriate to your `UCSBDiningCommonsMenuItem` table.  Be sure to get the API endpoint names correct for your `UCSBDiningCommonsMenuItem` table.

- [ ] Under `frontend/src/stories/pages/UCSBDiningCommonsMenuItem/` create a file called `UCSBDiningCommonsMenuItemCreatePage.stories.js` 
      modelled after the files `RestaurantCreatePage.stories.js` and/or `UCSBDatesCreatePage.stories.js`.

# Reminders (all from `frontend` directory):
      
* To run storybook locally: `npm run storybook`.
* To run tests locally: `npm test`.
* Quickly test coverage locally: `npm run coverage`
* Check linting locally: `npx eslint --fix .`
* Check mutation coverage locally (slow): `npx stryker run`
* Check mutation coverage of single file (faster): `npx stryker run -m src/main/pages/UCSBDiningCommonsMenuItem/UCSBDiningCommonsMenuItemCreatePage.js`

# What to do next

* Do a PR (following the usual steps).
* Check for other PRs 
* Start work on "Index Page for `UCSBDiningCommonsMenuItem` plus tests and stories"(following the usual steps for a new issue)

### PR DESCRIPTION
**Pull request by owenjpark**
For UCSBDiningCommonsMenuItem, added pages for index, create, and edit. Updated the App.js and AppNavbar.js to include these new pages. To test, make sure that you can create, edit, and view UCSBDiningCommonsMenuItems. Each item is supposed to have a "Name", "Dining Commons Code", and "Station". Dev deployment here: https://team03-owenjpark-dev.dokku-13.cs.ucsb.edu

Screenshot 2024-02-16 at 2 40 10 PM
Screenshot 2024-02-16 at 2 39 30 PM
Screenshot 2024-02-16 at 2 39 26 PM

Closes #12 
Closes #13

### CODE REVIEW

**Review by gretchenlam — APPROVED** [review]
LGTM! dev deployment fully functional

**Comment by Daoyijiucsb** [comment]
you should not delete placeholder in the Navbar. 
If other people also delete this and add the components at the same place, complie error would happen. 
Just add your conponents on the bottom.

**Review by Daoyijiucsb — DISMISSED** [review]
Don't delete placeholder components in the frontend/src/App.js
Add your components as a new line.

**Comment by Daoyijiucsb** [comment]
LGTM!

**Comment by Ze-el** [comment]
could you add the storybook link of the PR?

**Review by liamlizard — APPROVED** [review]
LGTM! Just add a storybook link and then I'll merge it. Also can you fix the merge conflicts?

**Comment by Ze-el** [comment]
Is this PR for placeholders or for the pages?

**Pull request closed without merging**
